global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9308']

  - job_name: 'gateway'
    static_configs:
      - targets: ['graphql-gateway:9200']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user_service:9201']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product_service:9202']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order_service:9203']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification_service:9204']

  - job_name: 'recommendation-service'
    static_configs:
      - targets: ['recommendation_service:9205']